serviceAccount:
    name: "iamproxy-service-account"
    annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/amp-iamproxy-role"
grafana.ini:
  auth:
    sigv4_auth_enabled: true
